---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: bionic

inputs:
  - name: pipeline-repo
outputs:
 - name: tf-source
params:
  PLUGIN_URL:
  PLUGIN_PATH:

run:
  path: pipeline-repo/tasks/install-tf-plugin/install-tf-plugin.sh
