#resources
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pks
  type: pivnet
  source:
    api_token: ((pivnet_api_token))
    product_slug: pivotal-container-service
    product_version: 1.7.0
    sort_by: semver
- name: pipeline-repo
  type: git
  source:
    uri: ((github_repo.uri))
    branch: master

- name: tf-state
  type: terraform
  source:
    backend_type: s3
    backend_config:
      key: terraform.tfstate
      workspace_key_prefix: ((pks.env_name))
      bucket: ((s3.buckets.terraform))
      region: us-east-1
      access_key: ((s3.buckets.access_key))
      secret_key: ((s3.buckets.secret_key))


jobs:

#create pks cluster 
- name: create-cluster
  public: false
  plan:
  - in_parallel:
    - get: pipeline-repo 
    - get: pks
      params:
        globs:
        - pks-linux*
  - task: create-cluster
    file: pipeline-repo/tasks/create-cluster/create-cluster.yml
    params:
      CLUSTER_NAME: ((pks.cluster_name))
      CLUSTER_HOSTNAME: ((pks.cluster_name)).((pks.dns_suffix))
      PKS_PLAN: ((pks.plan))
      PKS_PASSWORD: ((pks.password))
      PKS_USERNAME: ((pks.username))
      PKS_API: ((pks.api))



#create master load balancer 
- name: create-master-vip
  public: false
  plan:
  - in_parallel:
    - get: pipeline-repo 
      passed:
      - create-cluster
      trigger: true
    - get: pks
      params:
        globs:
        - pks-linux*
  - task: get-master-ips
    file: pipeline-repo/tasks/get-master-ips/get-master-ips.yml
    params:
      CLUSTER_NAME: ((pks.cluster_name))
      PKS_PASSWORD: ((pks.password))
      PKS_USERNAME: ((pks.username))
      PKS_API: ((pks.api))
  - task: install-citrix-plugin 
    file: pipeline-repo/tasks/install-tf-plugin/install-tf-plugin.yml
    params:
     PLUGIN_PATH: pipeline-repo/terraform/citrix/terraform.d/plugins/linux_amd64/
     PLUGIN_URL: https://github.com/citrix/terraform-provider-citrixadc/releases/download/v0.12.21/terraform-provider-citrixadc_0.12.21_linux_amd64.tar.gz
  - put: tf-state
    params:
      env:
        NS_URL: ((ns.url))
        NS_LOGIN: ((ns.user))
        NS_PASSWORD: ((ns.password))
      env_name: citrix
      terraform_source: tf-source/citrix
      delete_on_failure: false
      var_files:
      - k8s_vars/masters.tfvars
      vars:
        vip_ip: ((ns.vip_ip))
        pks_env: ((pks.env_name))
        cluster_name: ((pks.cluster_name))
  - task: ns-commit
    file: pipeline-repo/tasks/ns-commit/ns-commit.yml
    params:
      NS_URL: ((ns.url))
      NS_LOGIN: ((ns.user))
      NS_PASSWORD: ((ns.password))


# #add lb dns
- name: create-master-lb-dns
  public: false
  plan:
  - in_parallel:
    - get: pipeline-repo 
      passed:
      - create-master-vip
      trigger: true
  - task: install-infoblox-plugin 
    file: pipeline-repo/tasks/install-tf-plugin/install-tf-plugin.yml
    params:
     PLUGIN_PATH: pipeline-repo/terraform/master-dns/terraform.d/plugins/linux_amd64/
     PLUGIN_URL: https://infoblox-provider.s3.amazonaws.com/terraform-provider-infoblox.tar.gz
  - put: tf-state
    params:
      env_name: master-dns
      terraform_source: tf-source/master-dns
      delete_on_failure: false
      vars:
        vip_ip: ((ns.vip_ip))
        pks_env: ((pks.env_name))
        cluster_name: ((pks.cluster_name))
        dns_zone: ((infoblox.dns_zone))
        infoblox_server: ((infoblox.server))
        infoblox_user: ((infoblox.user))
        infoblox_password: ((infoblox.password))


#deploy netscaler crds

#deploy traefik

#create dns entry for ingress